@hostname = localhost 
@port = 5000
@host = http://{{hostname}}:{{port}}

GET {{host}}/api/v1/items

###


POST {{host}}/api/v1/items
Content-Type: application/json

{
    "name": "Burger King Bacon Meal",
    "quantity": 1
}


###

PUT {{host}}/api/v1/items
Content-Type: application/json

{
  "id": 2,
  "name": "Red Bull (still not sponsored)",
  "quantity": 1123
}

###

DELETE {{host}}/api/v1/items/2


